language: node_js
node_js:
  - 9
cache:
  directories:
    - $HOME/.npm
install:
  - npm ci
before_script:
  - npm run setup
script:
  - npm run test
  - npm run build
  - npm run build:lib
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
    local_dir: dist/app
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: dist/lib/*
    skip_cleanup: true
    on:
      tags: true
